# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.0.1
maven_group = plus.dragons.splashmilk
archives_name = splash_milk
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.1.2
neoforge_version = 26.1.2.94
