modLoader = "javafml" #mandatory
loaderVersion = "[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "splash_milk" #mandatory
version = "${version}" #mandatory
displayName = "Splash Milk" #mandatory
logoFile = "logo.png" #optional
authors = "MarbleGate" #optional
description = '''
Wait Steve, why don't you try putting milk in a potion bottle?
'''
[[dependencies.splash_milk]] #optional
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.splash_milk]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"