modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "splash_milk" #mandatory
version = "${version}" #mandatory
displayName = "Splash Milk" #mandatory
logoFile = "logo.png" #optional
authors = "MarbleGate" #optional
description = '''
Wait Steve, why don't you try putting milk in a potion bottle?
'''
[[dependencies.splash_milk]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.splash_milk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"