license = "MIT"
[[mods]] #mandatory
modId = "splash_milk" #mandatory
version = "${version}" #mandatory
displayName = "Splash Milk" #mandatory
logoFile = "icon.png" #optional
authors = "MarbleGate" #optional
description = '''
Wait Steve, why don't you try putting milk in a potion bottle?
'''
[[dependencies.splash_milk]] #optional
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.45-beta,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.splash_milk]]
modId = "minecraft"
type = "required"
versionRange = "[26.2]"
ordering = "NONE"
side = "BOTH"
